---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: web-app
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    env: dev
    namespace: dev
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80