---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    env: dev
  namespace: dev
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - name: http
          containerPort: 80
...