apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    env: dev
    namespace: dev
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
      - name: myapp
        protocol: TCP
        port: 80
        targetPort: 80